#Ohne Traefik
#version: '3.9'
#services:
 # web:
  #  build: .
   # command: python manage.py runserver 0.0.0.0:8000
   # volumes:
   #   - .:/code
   # ports:
    #  - "8000:8000"
    #depends_on:
    #  - db
 # db:
   # image: postgres:14
   # environment:
    # POSTGRES_DB: edu_db
    # POSTGRES_USER: edu_user
    #  POSTGRES_PASSWORD: edu_pass
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data/
#volumes:
#  postgres_data:

#Django-App mit Traefik erfolgt elegant über Docker-Labels, 
#die Traefik automatisch erkennt. Dadurch kannst du dynamisches Routing
#(per Subdomain oder Pfad) ohne manuelles Traefik-Konfigurationschaos umsetzen.
version: '3.8'

services:
  django:
    build:
      context: ./django_app
    container_name: edu_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edu_api.rule=Host(`edu.localhost`)"
      - "traefik.http.routers.edu_api.entrypoints=web"
      - "traefik.http.services.edu_api.loadbalancer.server.port=8000"
    networks:
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=edu_api.settings
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: edu
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: edupass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

volumes:
  pgdata:

networks:
  web:
    external: false
