# Base image & # syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project
COPY . /app

# Run gunicorn server
CMD ["gunicorn", "edu_api.wsgi:application", "--bind", "0.0.0.0:8000"]
# Collect static files
RUN python manage.py collectstatic --noinput