name: CI with traefik

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: edu_db
          POSTGRES_USER: edu#_user
          POSTGRES_PASSWORD: edupass#edu_pass
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout repo
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run tests
      env:
        DATABASE_URL: postgres://edu_user:edu_pass@localhost:5432/edu_db
      run: |
        cd django_app
        python manage.py migrate
        python app/manage.py test
    - name: Build Docker image
      run: |
        docker compose -f docker-compose.yml build

    # Optional: push to registry
    # - name: Log in to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push image
    #   run: docker tag app ghcr.io/your-username/edu-app && docker push ghcr.io/your-username/edu-app
